#!/usr/bin/env sh

# 🎨 Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RESET='\033[0m'

printf "\n${YELLOW}Executing pre-commit hook...${RESET}\n"

FILES_PATTERN='\.(js|ts)(\..+)?$'
FORBIDDEN='console\.[clear|dir|log|info|warn|error]'

#check for console. references in your code

if git diff --cached --name-only | \
    grep -E $FILES_PATTERN | \
    xargs grep --with-filename -n $FORBIDDEN | \
    grep -v '//';
then
    printf "\n${RED}COMMIT REJECTED!  Found console. references. Please remove them before committing.\n${no_color}"
    exit 1;
fi

FORBIDDEN='debugger'

#check for console. references in your code

if git diff --cached --name-only | \
    grep -E $FILES_PATTERN | \
    xargs grep --with-filename -n $FORBIDDEN | \
    grep -v '//';
then
    printf "\n${RED}COMMIT REJECTED!  Found debugger references. Please remove them before committing.\n${RESET}"
    exit 1;
fi

printf "${GREEN}No console. or debugger references found!${RESET}\n"
printf "${GREEN}Git pre-commit hook was successful!${RESET}\n"
exit 0;