name: Checks

on:
  workflow_call:

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - run: pnpm lint

  typecheck:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - run: pnpm typecheck

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - run: pnpm test
